--- #YAML:1.0
name:               Data-Predicate
version:            2.0.1
abstract:           ~
author:
    - "ayates" <"">
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Readonly:         0
    Scalar::Util:     0
    Test::Exception:  0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
